refactor: update lock file

diff --git a/.github/workflows/lockfileversion-check.yml b/.github/workflows/lockfileversion-check.yml
--- a/.github/workflows/lockfileversion-check.yml
+++ b/.github/workflows/lockfileversion-check.yml
@@ -1,13 +1,51 @@
-#check package-lock file version
+# Check package-lock file version and mismatch issues
 
-name: Lockfile Version check
+# This is a workflow to verify the use of NPM 9, lockfileVersion 3
+# and also detects mismatch between pacakge.json and package-lock.json.
+# This workflow intends to phase out the older workflow checking for lockfileVersion 2 & 3.
+
+name: lockfile check
 
 on:
   push:
     branches:
     - master
   pull_request:
-
 jobs:
   version-check:
-    uses: openedx/.github/.github/workflows/lockfileversion-check-v3.yml@master
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Retrieve version
+        id: getversion
+        run: |
+          echo "VERSION=$(cat package-lock.json | grep '\"lockfileVersion\": 3,')" >> $GITHUB_ENV
+
+      - name: Check value
+        if: ${{ env.VERSION == null }}
+        run: |
+          echo "ERROR: Outdated package-lock file. Use NPM9 to install dependencies "
+          exit 1
+
+  mismatch-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+
+      - name: Install node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+
+      - name: Check sync
+        run: |
+          error=$(npm ls --all --package-lock-only --json | jq '.error[]?' -r)
+          if [[ -n "$error" ]]; then
+            echo "$error"
+            echo
+            echo "Mismatch between package.json and package-lock.json. Please regenerate package lock file with 'npm install'."
+            exit 1
+          fi
